<?php

namespace EVO\UserBundle\Repository;

/**
 * ComprasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprasRepository extends \Doctrine\ORM\EntityRepository
{
}
